### ISSUE TITLE
Hang while importing messages

### ISSUE THREAD

**Issue by alex-taffe** [glaurent/MessagesHistoryBrowser#2] opened 2018-04-22 16:26 UTC
I just downloaded this app for the first time and went to import my messages. Everything seemed to be working at first. Then when the progress bar got to the end, it stayed there for a little bit and then the app locked up. It’s also using nearly 14gb of RAM (and steadily increasing) and has been running for over 30 minutes. I attached a sample of the process. My messages library is rather large so I’m not super surprised but something is still broken.
[Sample of MessagesHistoryBrowser.txt](https://github.com/glaurent/MessagesHistoryBrowser/files/1935831/Sample.of.MessagesHistoryBrowser.txt)

**Comment by glaurent** [comment] 2018-04-22 17:14
From the sample you posted it looks like it's stuck somewhere in CoreData, but I have no way to pinpoint the problem any further :-/. The problem with this app is that due to the private nature of the data it deals with, I can't ask people to send me their messages db to reproduce the problem. Is there any chance you can build it from source and see in Xcode where the problem is ?

**Comment by alex-taffe** [comment] 2018-04-22 18:23
Yeah sure, I’ll check it out

**Comment by alex-taffe** [comment] 2018-04-22 19:10
I struggled to actually find the calling code that was causing the issue, but it definitely is in core data. I attached the instruments session of the whole thing happening

[Instruments.trace.zip](https://github.com/glaurent/MessagesHistoryBrowser/files/1935995/Instruments.trace.zip)

**Comment by glaurent** [comment] 2018-04-22 21:54
Thanks, I'll try to take a look as soon as possible (which won't be before a while, I'm sorry :-/). Just to have an idea, how big is your ~/Library/Messages/chat.db ? Mine is 111Mb and the import takes about a minute to fully complete.

**Comment by alex-taffe** [comment] 2018-04-22 21:58
All good! And it’s 594.4 MB. Before the app freezes it takes around 6-10 minutes to get to the end of the loading bar. This is the system I’m running it on (only an SSD drive), so its not like anything is bottlenecking it

<img width="698" alt="screen shot 2018-04-22 at 5 57 10 pm" src="https://user-images.githubusercontent.com/6820226/39100349-ad87071a-4656-11e8-98c7-ced56030f6d8.PNG">

**Comment by glaurent** [comment] 2018-04-22 22:02
It feels like it's when I save the temporary CoreData context (merging it with the main one) that it's locking up... May be I should be doing intermediary saves every N messages imported.

I have a similar configuration as yours (identical except I only have 32Gb of RAM and a smaller graphics card), so yes it can't be your machine.

**Comment by alex-taffe** [comment] 2018-04-22 22:09
That could work, maybe even just dump the CoreData context handling to another thread? Like put a queue on that thread and every time you get a message, offload to that queue and have the second thread work through the queue at its own pace? I don’t have a ton of experience with CoreData so that may not be feasible but maybe?

**Comment by glaurent** [comment] 2018-04-22 22:14
It's already in another thread. I'm using Marcus Zarra's core data stack : http://martiancraft.com/blog/2015/03/core-data-stack/ . He's an authority of the subject, so I'm not sure where to go next.

**Comment by alex-taffe** [comment] 2018-04-23 12:04
It looks like that second thread is only spun up once the data is done being read in. After that it just crashes

**Comment by glaurent** [comment] 2018-04-23 14:36
Actually it's the opposite - the data is read in a secondary thread (and secondary CoreData store), then merged in the main store. I take it that merge is locking up for some reason.

**Comment by alex-taffe** [comment] 2018-04-23 14:39
Ahh my bad I just looked at that wrong then. And yeah that’s my assumption as well

**Comment by glaurent** [comment] 2018-04-23 14:46
Hold on, I was persuaded I was using Marcus Zarra's CoreData stack, but actually I'm not 🤭. I was confused because I've been using it in other apps. In here I'm just using the normal default stack as generated by Xcode templates. I guess that's a good reason to actually add it in.

**Comment by glaurent** [comment] 2018-05-08 22:54
Well, I looked again (in the right place), and actually yes I really was using Zarra's stack (🤭 again). So anyway, I've just pushed what should be a fix, can you update your tree and rebuild the app from source, and tell me if it works better ?  Thanks ☺️.

**Comment by glaurent** [comment] 2018-05-31 14:39
@alex-taffe any update on this ?

**Comment by alex-taffe** [comment] 2018-05-31 16:43
@glaurent my bad I totally forgot about this, lemme try it real quick!

**Comment by alex-taffe** [comment] 2018-05-31 16:56
Same issue sadly @glaurent 

[Instruments.trace.zip](https://github.com/glaurent/MessagesHistoryBrowser/files/2059217/Instruments.trace.zip)

**Comment by glaurent** [comment] 2018-05-31 16:59
From your trace you just left it running 1mn, given the size of your DB that's a bit short. Can you try again and let it run longer ? From my tests here there clearly was a big performance improvement with the intermediate CoreData saves I've added.

**Comment by alex-taffe** [comment] 2018-05-31 17:04
Yeah I had actually let it run for longer just from Xcode, but I noticed it had appeared to have frozen and then just transferred to instruments. Let me start it from scratch in instruments and I’ll let it run for like 30 mins-1 hour to see what it does

**Comment by alex-taffe** [comment] 2018-05-31 17:06
Actually interestingly, something must have happened because this time when I opened the application it was showing my contacts, which it has never done before. I just clicked file>refresh chat history and am letting it run in instruments so we’ll see if it finishes

**Comment by glaurent** [comment] 2018-05-31 17:08
Does the progress bar grow during the refresh ? It's likely to remain stuck for a little while at the very end, but overall it should finish normally.

**Comment by alex-taffe** [comment] 2018-05-31 17:38
It’s been going for 33 minutes so far and is stuck here right now. It’s been in “spinning” for about 10 minutes now

<img width="520" alt="screen shot 2018-05-31 at 1 37 56 pm" src="https://user-images.githubusercontent.com/6820226/40797976-df7d04f0-64d7-11e8-9bdf-bec16f150292.PNG">

**Comment by glaurent** [comment] 2018-05-31 17:40
OK, could you can pause it in Xcode and tell me where it's stuck ?

**Comment by alex-taffe** [comment] 2018-05-31 17:53
Sure lemme run again, here’s the instruments trace for that 44 mins or so
[Instruments3.trace.zip](https://github.com/glaurent/MessagesHistoryBrowser/files/2059423/Instruments3.trace.zip)

**Comment by alex-taffe** [comment] 2018-05-31 17:59
<img width="1512" alt="screen shot 2018-05-31 at 1 58 24 pm" src="https://user-images.githubusercontent.com/6820226/40799121-b9712fa4-64da-11e8-9280-3fc19d82fbfc.PNG">

Seems to always be pausing on `try localContext.save()`

**Comment by glaurent** [comment] 2018-05-31 18:06
Thanks, so my trick of saving the db at short intervals (once for every chat) instead of one time at the end of the populating does not fix the problem... Just how huge are your chats, really ? 😅

**Comment by alex-taffe** [comment] 2018-05-31 18:13
So on line 308 of that screenshot I put a `print("Saving for chat: \(chat.contact.name)")` to print out who it’s getting stuck on. The really weird thing is it’s not getting stuck on who I’d think. It plowed through my one friend who I have over 78,000 messages with in a few seconds but then someone who I have less than 500 with it gets stuck of for ages

**Comment by glaurent** [comment] 2018-05-31 18:21
I don't have any clue on what could happen here... I checked and there's an instrument for Core Data Saves, if you're in the mood to try that. I guess I'll add saves while collecting messages within a chat, and see how that works.

**Comment by alex-taffe** [comment] 2018-05-31 20:00
I can try that. It got stuck while saving chat chat10633056445688450 (CPU use down to 0% and hung for about 2 hours)

**Comment by alex-taffe** [comment] 2018-05-31 22:34
Here’s the trace of that (too big for GitHub)
https://drive.google.com/open?id=1_5YRO7_2tLAQgZ4zf0h84NGaFDd8Ogag

**Comment by glaurent** [comment] 2018-06-01 14:11
Thank you very much for your time. There seems to be a curse with this as Instruments hangs while trying to load it 😅. I'll repost here as soon as I have pushed the change on intermediary message saves.

**Comment by alex-taffe** [comment] 2018-06-01 15:48
If at any point you just decide that my insane message library isnt worth it, I totally understand haha

**Comment by glaurent** [comment] 2018-06-08 11:05
I've just pushed yet another tentative fix for the import - DB is saved every 300 messages now. Can you try and give it a spin ?

**Comment by alex-taffe** [comment] 2018-06-08 14:24
<img width="2003" alt="screen shot 2018-06-08 at 10 22 47 am" src="https://user-images.githubusercontent.com/6820226/41163176-fb43a6d8-6b05-11e8-8e75-56a5a9c14601.PNG">
It’s running, albeit decently slowly. It’s been going for about an hour and a half now and seems to be moving along. When I pause its usually on the `try localContext.save()` line

**Comment by glaurent** [comment] 2018-06-08 14:32
I must be missing something about Core Data performance, it shouldn't be taking so long.

**Comment by alex-taffe** [comment] 2018-06-08 18:55
Yeah its now been running for 6.5 hours and is still going

**Comment by glaurent** [comment] 2018-06-12 09:53
Did it finish eventually ?

**Comment by alex-taffe** [comment] 2018-06-12 12:15
No I let it run for about 13 hours and by then it was up to 23GB of used RAM so I had to kill it

**Comment by glaurent** [comment] 2018-06-12 12:50
So it's not just a Core Data performance issue... Thank you for your report, I'll take another crack at it.

**Comment by glaurent** [comment] 2018-06-16 13:58
After a few checks I just pushed another change. Can you give it another spin ? Thank you for your time.

**Comment by alex-taffe** [comment] 2018-06-16 14:40
I am actually traveling right now @glaurent and am away from the issue computer, but I set a reminder on my phone to check when I get back home

**Comment by glaurent** [comment] 2018-06-16 14:49
Thanks a lot :)

**Comment by glaurent** [comment] 2018-06-25 15:25
Are you still away from home ?

**Comment by alex-taffe** [comment] 2018-06-25 18:06
I am yes, I get back Saturday

**Comment by glaurent** [comment] 2018-06-25 18:21
ok ☺️ sorry for pressing you with this ☺️

**Comment by alex-taffe** [comment] 2018-06-25 20:08
All good! Can’t blame you for wanting to get it resolved

**Comment by alex-taffe** [comment] 2018-07-01 19:56
So I’m running the current version now and its been running for a little over 45 mins and is still going. Good news is the RAM is hovering at 4.22GB and not increasing. Only thing is it seems like the saving is being done on the main application thread which is causing the app to be in a constant state of beach ball. I’ll continue to let it run and report back

**Comment by glaurent** [comment] 2018-07-01 21:18
Thank you for the report. The save should happen on its own queue so I must still be doing something wrong. Is it still progressing or does it seem stuck at some point ?

**Comment by glaurent** [comment] 2018-07-04 13:48
Did it finish the import eventually ?

**Comment by alex-taffe** [comment] 2018-07-08 15:52
So it was using a ton of CPU for about 5 hours. Then the CPU usage went down to a spike every minute or so when `.save()` was triggered. I left it running for give or take 23 hours and then killed it. It seems as if the performance of `.save()` gets worse every time you call it, causing it to slow down exponentially.

**Comment by glaurent** [comment] 2018-07-09 09:32
Thank you for your report... I guess my CoreData stack is still broken somehow.

**Comment by glaurent** [comment] 2018-09-03 11:02
I've pushed a new branch 'coredata-stack-refactor' which uses the new NSPersistentContainer (but drops support of macOS 10.11 - 10.12+ is now required). Can you give it a try ?

**Comment by alex-taffe** [comment] 2018-09-03 15:12
I just tried it. That was the fastest I’ve ever seen the progress bar get to the point where the context begins saving. It then took a total of 58 minutes and 8.3GB of RAM for the progress bar to complete. Then the app hung with 100% CPU use on the main thread for another minute and a half before finishing up and dropping to 0% CPU. RAM is hovering at 7.76GB. But, the good news is that it actually loaded in a (somewhat) reasonable amount of time and appears to be working!

Also, you may want to warn people on that branch that you need Xcode 10 because of the Swift 4 change. I was super confused when it wasn't compiling at first but then realized it was Swift 4 haha

**Comment by alex-taffe** [comment] 2018-09-03 15:14
Quitting the app and restarting it, thread list loads instantly and threads themselves load relatively quickly. Each thread that gets opened though tacks on between 350MB-1.2GB of RAM usage

**Comment by glaurent** [comment] 2018-09-03 15:44
Good news :-). Yes it's normal that on restart, the app will load instantly : your Messages DB has been fully imported in the app's own DB, and from then on, until you redo an import (cmd-R), the app will access its own DB only.

That said, your messages DB must really be quite large for this to happen. How big is the DB in ~/Library/Application\ Support/MessagesHistoryBrowser ?

**Comment by alex-taffe** [comment] 2018-09-03 16:02
```
Alexs-iMac:~ Alex$ ls -lah ~/Library/Application\ Support/MessagesHistoryBrowser
total 3905736
drwxr-xr-x    5 Alex  staff   160B Sep  3 10:09 .
drwx------  346 Alex  staff    11K Sep  3 10:09 ..
-rw-r--r--    1 Alex  staff   1.9G Sep  3 11:08 MessagesHistoryBrowser.sqlite
-rw-r--r--    1 Alex  staff    32K Sep  3 11:13 MessagesHistoryBrowser.sqlite-shm
-rw-r--r--    1 Alex  staff   3.0M Sep  3 11:08 MessagesHistoryBrowser.sqlite-wal
```

**Comment by glaurent** [comment] 2018-09-03 19:27
Thanks. 1.9G is huge, my MessagesHistoryBrowser.sqlite is 21M. I can understand why the import took so long in your case.

Anyway, if you agree I'll close this issue, given the new CoreData stack I'm using (NSPersistentContainer), I don't see any other paths for improvement.

**Comment by alex-taffe** [comment] 2018-09-03 19:45
Yep, seems good to me

**Comment by glaurent** [comment] 2018-09-04 10:10
Fixed in coredata-stack-refactor branch, merged in master.

**Closed as completed by glaurent** 2018-09-04 10:10 UTC
